/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CST707TermProject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author JamesAndAmber
 */
public class VGDB_GUI extends javax.swing.JFrame {

    /**
     * Creates new form VGDB_GUI
     */
    public VGDB_GUI() {
        initComponents();
        
//        jTable1.getSelectionModel().addListSelectionListener(
//        new ListSelectionListener() {
//            public void valueChanged(ListSelectionEvent event) {
//                mod_gName.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
//                mod_gDate.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
//                mod_gGenre.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
//                mod_gRating.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
//                mod_gStudio.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
//                mod_gEngine.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
//                mod_gPublisher.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
//                mod_gFranchise.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
//            }
//        }
//);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        s_gameName = new javax.swing.JTextField();
        s_genre = new javax.swing.JTextField();
        s_releaseDate = new javax.swing.JTextField();
        s_franchiseName = new javax.swing.JTextField();
        s_parentalRating = new javax.swing.JTextField();
        s_studioName = new javax.swing.JTextField();
        s_publisherName = new javax.swing.JTextField();
        s_engineName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mod_gName = new javax.swing.JTextField();
        mod_gGenre = new javax.swing.JTextField();
        mod_gDate = new javax.swing.JTextField();
        mod_gFranchise = new javax.swing.JTextField();
        mod_gRating = new javax.swing.JTextField();
        mod_gStudio = new javax.swing.JTextField();
        mod_gPublisher = new javax.swing.JTextField();
        mod_gEngine = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Search By...");

        s_gameName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_gameNameActionPerformed(evt);
            }
        });

        s_genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_genreActionPerformed(evt);
            }
        });

        s_releaseDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_releaseDateActionPerformed(evt);
            }
        });

        s_franchiseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_franchiseNameActionPerformed(evt);
            }
        });

        s_parentalRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_parentalRatingActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("Genre");

        jLabel5.setText("Date Released");

        jLabel6.setText("Franchise");

        jLabel7.setText("Rating");

        jLabel8.setText("Studio");

        jLabel9.setText("Publisher");

        jLabel10.setText("Engine");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(s_gameName, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(s_genre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 22, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(s_releaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(s_franchiseName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(s_parentalRating, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(s_studioName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(s_publisherName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(s_engineName, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(80, 80, 80))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(40, 40, 40)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_gameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_releaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_franchiseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_parentalRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_studioName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_publisherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_engineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        jLabel2.setText("Modify");
        jLabel2.setToolTipText("");

        mod_gName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_gNameActionPerformed(evt);
            }
        });

        jButton2.setText("Submit Change");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Name");

        jLabel12.setText("Genre");

        jLabel13.setText("Date Released");

        jLabel14.setText("Franchise");

        jLabel15.setText("Rating");

        jLabel16.setText("Studio");

        jLabel17.setText("Publisher");

        jLabel18.setText("Engine");

        jPanel3.setBackground(new java.awt.Color(83, 90, 92));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12))
                            .addComponent(jLabel13)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mod_gGenre, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(mod_gDate)
                            .addComponent(mod_gRating)
                            .addComponent(mod_gName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mod_gStudio, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(mod_gEngine)
                            .addComponent(mod_gPublisher)
                            .addComponent(mod_gFranchise))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(350, 350, 350))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(309, 309, 309))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mod_gName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(mod_gStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mod_gGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(mod_gEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mod_gDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(mod_gPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mod_gRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(mod_gFranchise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(35, 35, 35))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Date Released", "Genre", "Rating", "Studio", "Engine", "Publisher", "Franchise"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s_gameNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_gameNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_gameNameActionPerformed

    private void s_genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_genreActionPerformed

    private void s_franchiseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_franchiseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_franchiseNameActionPerformed

    private void s_parentalRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_parentalRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_parentalRatingActionPerformed

    private void s_releaseDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_releaseDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_releaseDateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //String q_gameName = s_gameName.getText();
        
    try{
        
        Connection conn = DriverManager.getConnection ("jdbc:mysql://localhost:3306/jjackson?user=jjackson&password=Amricap1");

        String beginConstraint = "SELECT gameName, `Release Date`, Genre, ParentalRating, studioName, engineName, publisherName, franchiseName FROM jjackson.Game " +
                                    "JOIN jjackson.Studio ON Game.Studio_idStudio = Studio.idStudio " +
                                    "JOIN jjackson.`Engine` ON Game.Engine_idEngine = `Engine`.idEngine " +
                                    "JOIN jjackson.Publisher ON Game.Publisher_idPublisher = Publisher.idPublisher " +
                                    "JOIN jjackson.Franchise ON Game.Franchise_idFranchise = Franchise.idFranchise ";
        Boolean isFirstCons = true;
        
        //-------------Search Name---------------------
        
        String nameCons = s_gameName.getText();
        if(nameCons.length() == 0){
            // Skip to next Contraint
        }else{
            nameCons = "WHERE Game.gameName LIKE '%" + nameCons + "%'";
            isFirstCons = false;
        }
        
        //-------------Search Genre---------------------
        
        String genreCons = s_genre.getText();
        if(genreCons.length() == 0){
            // Skip to next Contraint
        }else{
            if(isFirstCons == true){
                genreCons = "WHERE Genre LIKE '%" + genreCons + "%' ";
                isFirstCons = false;
            }
            else{
                genreCons = "AND Genre LIKE '%" + genreCons + "%' ";
            }
        }
        
        //-------------Search Date---------------------
        String dateCons = s_releaseDate.getText();
        if(dateCons.length() == 0){
            // Skip to next Contraint
        }else{
            if(isFirstCons == true){
                dateCons = "WHERE `Release Date` LIKE '%" + dateCons + "%' ";
                isFirstCons = false;
            }
            else{
                dateCons = "AND `Release Date` LIKE '%" + dateCons + "%' ";
            }
        }
        
        //-------------Search Rating---------------------
        String ratingCons = s_parentalRating.getText();
        if(ratingCons.length() == 0){
            // Skip to next Contraint
        }else{
            if(isFirstCons == true){
                ratingCons = "WHERE ParentalRating LIKE '%" + ratingCons + "%' ";
                isFirstCons = false;
            }
            else{
                ratingCons = "AND ParentalRating LIKE '%" + ratingCons + "%' ";
            }
        }
        //-------------Search Franchise---------------------
        
        String franchiseCons = s_franchiseName.getText();
        if(franchiseCons.length() == 0){
            // Skip to next Contraint
        }else{
            if(isFirstCons == true){
                franchiseCons = "WHERE franchiseName LIKE '%" + franchiseCons + "%' ";
                isFirstCons = false;
            }
            else{
                franchiseCons = "AND franchiseName LIKE '%" + franchiseCons + "%' ";
            }
        }
        
        //-------------Search Studio---------------------
        
        String studioCons = s_studioName.getText();
        if(studioCons.length() == 0){
            // Skip to next Contraint
        }else{
            if(isFirstCons == true){
                studioCons = "WHERE studioName LIKE '%" + studioCons + "%' ";
                isFirstCons = false;
            }
            else{
                studioCons = "AND studioName LIKE '%" + studioCons + "%' ";
            }
        }
        
        //-------------Search Publisher---------------------
        
        String publisherCons = s_publisherName.getText();
        if(publisherCons.length() == 0){
            // Skip to next Contraint
        }else{
            if(isFirstCons == true){
                publisherCons = "WHERE publisherName LIKE '%" + publisherCons + "%' ";
                isFirstCons = false;
            }
            else{
                publisherCons = "AND publisherName LIKE '%" + publisherCons + "%' ";
            }
        }
        
        //-------------Search Engine---------------------
        
        String engineCons = s_engineName.getText();
        if(engineCons.length() == 0){
            // Skip to next Contraint
        }else{
            if(isFirstCons == true){
                engineCons = "WHERE engineName LIKE '%" + engineCons + "%' ";
                isFirstCons = false;
            }
            else{
                engineCons = "AND engineName LIKE '%" + engineCons + "%' ";
            }
        }
        
        
        String fullConstraint = beginConstraint + nameCons + genreCons
                + dateCons + franchiseCons + ratingCons + studioCons
                + publisherCons + engineCons; 
        
        String createString = fullConstraint;

        java.sql.Statement stmt = null;

        try {
            
            stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(createString);
            System.out.println("Query Success!!");
            
            //To remove previously added rows
            while(jTable1.getRowCount() > 0) 
            {
                ((DefaultTableModel) jTable1.getModel()).removeRow(0);
            }
            int columns = rs.getMetaData().getColumnCount();
            while(rs.next())
            {  
                Object[] row = new Object[columns];
                for (int i = 1; i <= columns; i++)
                {  
                    row[i - 1] = rs.getObject(i);
                }
                ((DefaultTableModel) jTable1.getModel()).insertRow(rs.getRow()-1,row);
            }
        }

        finally {
            if (stmt != null) { stmt.close(); }
        }
        
    }catch(SQLException ex){
        System.out.println("Invalid SQL. The Error was: " + ex.getMessage());
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mod_gNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_gNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mod_gNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //TODO
        //TODO
        //TODO
        
//        try{
//        
//        Connection conn = DriverManager.getConnection ("jdbc:mysql://localhost:3306/jjackson?user=jjackson&password=Amricap1");
//
//
//        Boolean isFirstCons = true;
//        
//        //-------------Search Name---------------------
//        
//        String nameCons = s_gameName.getText();
//        if(nameCons.length() == 0){
//            // Skip to next Contraint
//        }else{
//            nameCons = "WHERE Game.gameName LIKE '%" + nameCons + "%'";
//        }
//        
//        //-------------Search Genre---------------------
//        
//        String genreCons = s_genre.getText();
//        if(genreCons.length() == 0){
//            // Skip to next Contraint
//        }else{
//                genreCons = "WHERE Genre LIKE '%" + genreCons + "%' ";
//        }
//        
//        //-------------Search Date---------------------
//        String dateCons = s_releaseDate.getText();
//        if(dateCons.length() == 0){
//            // Skip to next Contraint
//        }else{
//            if(isFirstCons == true){
//                dateCons = "WHERE `Release Date` LIKE '%" + dateCons + "%' ";
//                isFirstCons = false;
//            }
//            else{
//                dateCons = "AND `Release Date` LIKE '%" + dateCons + "%' ";
//            }
//        }
//        
//        //-------------Search Rating---------------------
//        String ratingCons = s_parentalRating.getText();
//        if(ratingCons.length() == 0){
//            // Skip to next Contraint
//        }else{
//            if(isFirstCons == true){
//                ratingCons = "WHERE ParentalRating LIKE '%" + ratingCons + "%' ";
//                isFirstCons = false;
//            }
//            else{
//                ratingCons = "AND ParentalRating LIKE '%" + ratingCons + "%' ";
//            }
//        }
//        //-------------Search Franchise---------------------
//        
//        String franchiseCons = s_franchiseName.getText();
//        if(franchiseCons.length() == 0){
//            // Skip to next Contraint
//        }else{
//            if(isFirstCons == true){
//                franchiseCons = "WHERE franchiseName LIKE '%" + franchiseCons + "%' ";
//                isFirstCons = false;
//            }
//            else{
//                franchiseCons = "AND franchiseName LIKE '%" + franchiseCons + "%' ";
//            }
//        }
//        
//        //-------------Search Studio---------------------
//        
//        String studioCons = s_studioName.getText();
//        if(studioCons.length() == 0){
//            // Skip to next Contraint
//        }else{
//            if(isFirstCons == true){
//                studioCons = "WHERE studioName LIKE '%" + studioCons + "%' ";
//                isFirstCons = false;
//            }
//            else{
//                studioCons = "AND studioName LIKE '%" + studioCons + "%' ";
//            }
//        }
//        
//        //-------------Search Publisher---------------------
//        
//        String publisherCons = s_publisherName.getText();
//        if(publisherCons.length() == 0){
//            // Skip to next Contraint
//        }else{
//            if(isFirstCons == true){
//                publisherCons = "WHERE publisherName LIKE '%" + publisherCons + "%' ";
//                isFirstCons = false;
//            }
//            else{
//                publisherCons = "AND publisherName LIKE '%" + publisherCons + "%' ";
//            }
//        }
//        
//        //-------------Search Engine---------------------
//        
//        String engineCons = s_engineName.getText();
//        if(engineCons.length() == 0){
//            // Skip to next Contraint
//        }else{
//            if(isFirstCons == true){
//                engineCons = "WHERE engineName LIKE '%" + engineCons + "%' ";
//                isFirstCons = false;
//            }
//            else{
//                engineCons = "AND engineName LIKE '%" + engineCons + "%' ";
//            }
//        }
//        
//        
//        String fullConstraint = beginConstraint + nameCons + genreCons
//                + dateCons + franchiseCons + ratingCons + studioCons
//                + publisherCons + engineCons; 
//        
//        String createString = fullConstraint;
//
//        java.sql.Statement stmt = null;
//
//        try {
//            
//            stmt = conn.createStatement();
//            ResultSet rs = stmt.executeQuery(createString);
//            System.out.println("Query Success!!");
//            
//            //To remove previously added rows
//            while(jTable1.getRowCount() > 0) 
//            {
//                ((DefaultTableModel) jTable1.getModel()).removeRow(0);
//            }
//            int columns = rs.getMetaData().getColumnCount();
//            while(rs.next())
//            {  
//                Object[] row = new Object[columns];
//                for (int i = 1; i <= columns; i++)
//                {  
//                    row[i - 1] = rs.getObject(i);
//                }
//                ((DefaultTableModel) jTable1.getModel()).insertRow(rs.getRow()-1,row);
//            }
//        }
//
//        finally {
//            if (stmt != null) { stmt.close(); }
//        }
//        
//    }catch(SQLException ex){
//        System.out.println("Invalid SQL. The Error was: " + ex.getMessage());
//    }
//        
//        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VGDB_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VGDB_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VGDB_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VGDB_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VGDB_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mod_gDate;
    private javax.swing.JTextField mod_gEngine;
    private javax.swing.JTextField mod_gFranchise;
    private javax.swing.JTextField mod_gGenre;
    private javax.swing.JTextField mod_gName;
    private javax.swing.JTextField mod_gPublisher;
    private javax.swing.JTextField mod_gRating;
    private javax.swing.JTextField mod_gStudio;
    private javax.swing.JTextField s_engineName;
    private javax.swing.JTextField s_franchiseName;
    private javax.swing.JTextField s_gameName;
    private javax.swing.JTextField s_genre;
    private javax.swing.JTextField s_parentalRating;
    private javax.swing.JTextField s_publisherName;
    private javax.swing.JTextField s_releaseDate;
    private javax.swing.JTextField s_studioName;
    // End of variables declaration//GEN-END:variables
}
